spring.application.name=administrador_de_tareas_domesticas

spring.datasource.url=jdbc:postgresql://dpg-d7n4ruvavr4c73fdioug-a.ohio-postgres.render.com/administrador_de_tareas_domesticas
spring.datasource.username=admin
spring.datasource.password=CWQSO5RkVx4IwYvIClXsvwR4djfBgw3R

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
server.port=8080
